/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ControladorUsuario;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    ControladorUsuario gestionUsuario;

    /**
     * Creates new form JfrmLogin
     */
    public Login() {

        initComponents();
        setLocationRelativeTo(this);
        gestionUsuario = new ControladorUsuario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        usuario1 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnRegistrarUsuario = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei UI Light", 1, 18))); // NOI18N
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario1.setText("Contraseña");
        panel.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        usuario2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        usuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario2.setText("Correo");
        panel.add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        txtCorreo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(181, 181, 181));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText("Ingrese su correo electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        panel.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 190, 30));

        txtContra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContra.setForeground(new java.awt.Color(181, 181, 181));
        txtContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContra.setText("********");
        txtContra.setBorder(null);
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        panel.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, 30));

        btnEntrar.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        panel.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 30));

        btnRegistrarUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnRegistrarUsuario.setText("Crear cuenta");
        btnRegistrarUsuario.setBorderPainted(false);
        btnRegistrarUsuario.setContentAreaFilled(false);
        btnRegistrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarUsuarioMouseExited(evt);
            }
        });
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        panel.add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 120, 20));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (txtCorreo.getText().equals("Ingrese su correo electronico")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (String.valueOf(txtContra.getPassword()).isEmpty()) {
            txtContra.setText("********");
            txtContra.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtContra.getPassword()).equals("********")) {
            txtContra.setText("");
            txtContra.setForeground(Color.black);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("Ingrese su correo electronico");
            txtCorreo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtContraMousePressed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        String correo = txtCorreo.getText().trim();
        String contrasenia = txtContra.getText().trim();

        if (!correo.equals("Ingrese su correo electronico") && !contrasenia.equals("********")) {
        
            Menu vu = new Menu();
            vu.setVisible(true);
            this.setVisible(false);
            txtCorreo.setText("Ingrese su nombre de usuario");
            txtCorreo.setForeground(Color.gray);
            txtContra.setText("********");
            txtContra.setForeground(Color.gray);

        } else {
            JOptionPane.showMessageDialog(null, "Por favor debe "
                    + "llenar los campos vacíos");

        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnRegistrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioMouseEntered
        // TODO add your handling code here:
        btnRegistrarUsuario.setForeground(Color.gray);
    }//GEN-LAST:event_btnRegistrarUsuarioMouseEntered

    private void btnRegistrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioMouseExited
        // TODO add your handling code here:
        btnRegistrarUsuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnRegistrarUsuarioMouseExited

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:

        Registrarse ventana = new Registrarse();
        ventana.setVisible(true);
        this.dispose();
        txtCorreo.setText("Ingrese su nombre de usuario");
        txtCorreo.setForeground(Color.gray);
        txtContra.setText("********");
        txtContra.setForeground(Color.gray);
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    // End of variables declaration//GEN-END:variables
}
