/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ControladorArticulo;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Articulo;

/**
 *
 * @author Juan Potes
 */
public class RegistroArticulos extends javax.swing.JFrame {

    private Menu ventana;
    ControladorArticulo gestionArticulo;

    /**
     * Creates new form JfrmRegistroArticulos
     */
    public RegistroArticulos() {
        initComponents();
        gestionArticulo = new ControladorArticulo();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        BtnBuscarArticulo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JToggleButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Articulos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Codigo");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 25));
        bg.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 25));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 25));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Precio");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 25));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 25));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descripción");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 25));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, 25));
        bg.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 120, 25));
        bg.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 25));
        bg.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 120, 25));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 25));

        BtnBuscarArticulo.setText("Buscar");
        BtnBuscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarArticuloActionPerformed(evt);
            }
        });
        bg.add(BtnBuscarArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, 25));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bg.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, 25));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 25));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 420));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(TablaArticulos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 432, 93));

        btnRegresar.setText("Atras");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 460, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();

        if (gestionArticulo.eliminar(codigo)) {
            JOptionPane.showMessageDialog(this, "Has Eliminado el articulo exitosamente");
            llenarTabla();
            limpiar();

        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar el articulo");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void BtnBuscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarArticuloActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();

        if (!codigo.equals("")) {

            Articulo articulo = gestionArticulo.buscar(codigo);
            if (articulo != null) {
                txtNombre.setText(articulo.getNombre());
                txtPrecio.setText(String.valueOf(articulo.getPrecio()));
                txtCantidad.setText(String.valueOf(articulo.getCantidad()));
                txtDescripcion.setText(articulo.getDescripcion());
                txtCodigo.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Articulo encontrado");
            } else {
                limpiar();
                JOptionPane.showMessageDialog(this, "No se encuentra el Articulo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el dato que desea buscar");
        }
    }//GEN-LAST:event_BtnBuscarArticuloActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();
        String nombre = txtNombre.getText();
        double precio = Double.parseDouble(txtPrecio.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String descripcion = txtDescripcion.getText();

        if (gestionArticulo.modificar(codigo, nombre, precio, cantidad, descripcion)) {
            JOptionPane.showMessageDialog(this, "Modificado exitosamente");
            llenarTabla();
            limpiar();

        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();
        String nombre = txtNombre.getText();
        double precio = Double.parseDouble(txtPrecio.getText());
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String descripcion = txtDescripcion.getText();
        if (gestionArticulo.guardar(codigo, nombre, precio, cantidad, descripcion)) {
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            llenarTabla();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed
    public void limpiar() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtDescripcion.setText("");
        txtCodigo.setText("");
    }

    public void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        List<Articulo> lista = gestionArticulo.obtenerLista();
        model.setColumnIdentifiers(new Object[]{" codigo", "nombre", " precio", "cantidad", " descripcion",});
        TablaArticulos.setModel(model);
        for (int i = 0; i < lista.size(); i++) {
            model.addRow(new Object[]{
                lista.get(i).getCodigo(),
                lista.get(i).getNombre(),
                lista.get(i).getPrecio(),
                lista.get(i).getCantidad(),
                lista.get(i).getDescripcion(),});

        }
    }

//////    /**
//////     * @param args the command line arguments
//////     */
//////    public static void main(String args[]) {
//////        /* Set the Nimbus look and feel */
//////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//////         */
//////        try {
//////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//////                if ("Nimbus".equals(info.getName())) {
//////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//////                    break;
//////                }
//////            }
//////        } catch (ClassNotFoundException ex) {
//////            java.util.logging.Logger.getLogger(RegistroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (InstantiationException ex) {
//////            java.util.logging.Logger.getLogger(RegistroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (IllegalAccessException ex) {
//////            java.util.logging.Logger.getLogger(RegistroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//////            java.util.logging.Logger.getLogger(RegistroArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////        }
//////        //</editor-fold>
//////        //</editor-fold>
//////
//////        /* Create and display the form */
//////        java.awt.EventQueue.invokeLater(new Runnable() {
//////            public void run() {
////////                new RegistroArticulos().setVisible(true);
//////            }
//////        });
//////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarArticulo;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JToggleButton btnRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
