/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ControladorUsuario;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Registrarse extends javax.swing.JFrame {

    ControladorUsuario gestionUsuario;

    /**
     * Creates new form JfrmRegistroLogin
     */
    public Registrarse() {
        initComponents();

        gestionUsuario = new ControladorUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro2 = new javax.swing.JPanel();
        labelNombre2 = new javax.swing.JLabel();
        txtCEDULA = new javax.swing.JTextField();
        labelCedula2 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        labelApellido2 = new javax.swing.JLabel();
        txtAPELLIDO = new javax.swing.JTextField();
        labelCorreo2 = new javax.swing.JLabel();
        txtCORREO = new javax.swing.JTextField();
        labelContraseña2 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistro2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        panelRegistro2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre2.setText("Cedula");
        panelRegistro2.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        txtCEDULA.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        txtCEDULA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCEDULA.setBorder(null);
        panelRegistro2.add(txtCEDULA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        labelCedula2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelCedula2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCedula2.setText("Nombre");
        panelRegistro2.add(labelCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 30));

        txtNOMBRE.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        txtNOMBRE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNOMBRE.setBorder(null);
        panelRegistro2.add(txtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, -1));

        labelApellido2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelApellido2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellido2.setText("Apellido");
        panelRegistro2.add(labelApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 30));

        txtAPELLIDO.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        txtAPELLIDO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAPELLIDO.setBorder(null);
        panelRegistro2.add(txtAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, -1));

        labelCorreo2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelCorreo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCorreo2.setText("Correo");
        panelRegistro2.add(labelCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 30));

        txtCORREO.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        txtCORREO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCORREO.setBorder(null);
        panelRegistro2.add(txtCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 150, -1));

        labelContraseña2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        labelContraseña2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContraseña2.setText("Contraseña");
        panelRegistro2.add(labelContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, 30));

        txtContra.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        txtContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContra.setBorder(null);
        panelRegistro2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelRegistro2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btnAgregar.setText("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelRegistro2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        getContentPane().add(panelRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Login ventana = new Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCEDULA.getText();
        String nombre = txtNOMBRE.getText();
        String apellido = txtAPELLIDO.getText();
        String correo = txtCORREO.getText();
        String contrasenia = txtContra.getText();

        if (gestionUsuario.guardar(cedula, nombre, apellido, correo, contrasenia)) {
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            Menu ventana = new Menu();
            ventana.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new Registrarse().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelApellido1;
    private javax.swing.JLabel labelApellido2;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCedula1;
    private javax.swing.JLabel labelCedula2;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelContraseña1;
    private javax.swing.JLabel labelContraseña2;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelCorreo1;
    private javax.swing.JLabel labelCorreo2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelRegistro1;
    private javax.swing.JPanel panelRegistro2;
    private javax.swing.JTextField txtAPELLIDO;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCEDULA;
    private javax.swing.JTextField txtCORREO;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtContraseña1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
